spring:
  application:
    name: scrapy-scrapy
  
  # R2DBC Configuration
  r2dbc:
    pool:
      enabled: true
      initial-size: 5
      max-size: 10
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:scrapyscrapy}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  
  # Flyway Configuration
  flyway:
    enabled: false  # Disabled by default
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:scrapyscrapy}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: false
  
  # Security Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER:http://localhost:8080}
          secret: ${JWT_SECRET}
          expiration: ${JWT_EXPIRATION}
    user:
      name: ${SECURITY_USER:user}
      password: ${SECURITY_PASSWORD:password}
  
  # Jackson Configuration
  jackson:
    default-property-inclusion: non-null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# Logging Configuration
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) [%blue(%t)] %yellow(%C{1}): %msg%n%throwable"
  level:
    root: INFO
    com.scrapyscrapy: DEBUG
    org.springframework:
      web: INFO
      security: INFO
      data.r2dbc: DEBUG
    io.r2dbc: DEBUG

# Management/Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
      cors:
        allowed-origins: "*"
        allowed-methods: GET
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
      probes:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# Server Configuration
server:
  port: 8080
  shutdown: graceful
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

# Springdoc OpenAPI Configuration
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  show-actuator: true

# Create dev profile specific config
---
spring:
  config:
    activate:
      on-profile: dev
  flyway:
    enabled: ${FLYWAY_ENABLED:false}  # Enable only in dev profile 